version: "3.9"

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: rental_admin

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    container_name: rental_customer

  vendor:
    build:
      context: ./vendor
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    container_name: rental_vendor
