name: Deploy Admin to R2

on:
  push:
    branches:
      - main
    paths:
      - 'admin/**'
      - '!vendor/**'
      - '!customer/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./admin

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Vite project
        run: yarn build

      - name: Install Wrangler CLI + jq
        run: |
          npm install -g wrangler
          sudo apt-get install -y jq

      - name: Clean R2 bucket before upload
        run: |
          wrangler r2 object list rentpe-admin --json \
          | jq -r '.[].key' \
          | xargs -r -I {} wrangler r2 object delete rentpe-admin --key "{}"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Upload latest dist to R2
        run: |
          wrangler r2 object put rentpe-admin --file dist --recursive
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}